/** Field visibility and labels per document type — shared ERP document template. */

export const DOC_TYPES = {
  invoice: {
    title: "Tax Invoice",
    footerText: "This is a Computer Generated Invoice",
    partyBillLabel: "Buyer (Bill to)",
    partyShipLabel: "Consignee (Ship to)",
    docNoLabel: "Invoice No.",
    docDateLabel: "Invoice Date",
    showEInvoice: true,
    showEwayBill: true,
    showDueDate: true,
    showPaymentDetails: true,
    showValidUntil: false,
    showSalesPerson: false,
    showDeliveryTerms: true,
    showRejectionPolicy: true,
  },
  quotation: {
    title: "Quotation",
    footerText: "This is a Computer Generated Quotation",
    partyBillLabel: "Buyer (Bill to)",
    partyShipLabel: "Consignee (Ship to)",
    docNoLabel: "Quote No.",
    docDateLabel: "Quotation Date",
    showEInvoice: true,
    showEwayBill: false,
    showDueDate: false,
    showPaymentDetails: true,
    showValidUntil: true,
    showSalesPerson: true,
    showDeliveryTerms: true,
    showRejectionPolicy: false,
    headerRightLabel: "e-Quotation",
    remarksPrefix: "Being material sold vide Quotation No. :",
    policyHeading: "Quotation Policy :",
  },
  purchase: {
    title: "PURCHASE",
    footerText: "This is a Computer Generated Purchase Document",
    partyBillLabel: "Supplier (Bill from)",
    partyShipLabel: "Delivery Address",
    docNoLabel: "Purchase No.",
    docDateLabel: "Purchase Date",
    showEInvoice: false,
    showEwayBill: false,
    showDueDate: true,
    showPaymentDetails: true,
    showValidUntil: false,
    showSalesPerson: false,
    showDeliveryTerms: false,
    showRejectionPolicy: false,
  },
  proforma: {
    title: "Proforma Invoice",
    footerText: "This is a Computer Generated Proforma Invoice",
    partyBillLabel: "Buyer (Bill to)",
    partyShipLabel: "Consignee (Ship to)",
    docNoLabel: "Proforma No.",
    docDateLabel: "Proforma Date",
    showEInvoice: false,
    showEwayBill: true,
    showDueDate: true,
    showPaymentDetails: true,
    showValidUntil: true,
    showSalesPerson: true,
    showDeliveryTerms: true,
    showRejectionPolicy: true,
  },
  export_proforma: {
    title: "Export Proforma Invoice",
    footerText: "This is a Computer Generated Export Proforma Invoice",
    partyBillLabel: "Buyer (Bill to)",
    partyShipLabel: "Consignee (Ship to)",
    docNoLabel: "Proforma No.",
    docDateLabel: "Proforma Date",
    showEInvoice: false,
    showEwayBill: true,
    showDueDate: true,
    showPaymentDetails: true,
    showValidUntil: true,
    showSalesPerson: true,
    showDeliveryTerms: true,
    showRejectionPolicy: true,
  },
};

export function getDocConfig(docType) {
  return DOC_TYPES[docType] || DOC_TYPES.invoice;
}
